### PR TITLE
Database rework

### PR DESCRIPTION
**Pull request by MaximeHollebecq**
This pull request is made to solve the issue #14 and #13 .

The first change is on the logging screen where the user can add an optionnal comment about the run he is about to do. 
image

This comment will be pushed on the database if the user decide to push the data.
image

The interface is now reworked to fit with the mokup on the issue. 
After the user stop logging the data , he can :
- push the data on the database .
- save the data on a csv file on the local disk.
image

If the user choose to push the data or save , the button turn to gray with a chekmark and cannot be pressed again. the title also indicate where the csv file is logged.
image

### CODE REVIEW

**Comment by MaximeHollebecq** [comment]
@bastianilso the changes are now done about the database / network connection with the title display.
image
however , a dump file is created if the user is offline , the data in the dump folder will be pushed next time the user run the app.

The buttons are also now displaying a finished text when they are pressed. 
image

**Comment by bastianilso** [comment]
@MaximeHollebecq cool, almost there - It is fine that the buttons turn dark grey (like you first did), but I am saying the _text_ should be grey.  😃 Like in the screenshot below:
image

**Comment by MaximeHollebecq** [comment]
@bastianilso  the button + text are now on grey when the button is pressed 
image

**Comment by Adel-Akbi** [comment]
Evrything seems great to me, well done @MaximeHollebecq 🥇

**Pull request merged**
